apiVersion: v1
kind: Service                    
metadata:
  name: stargazer-server
spec:
  type: NodePort                 
  ports:                         
  - port: 8080
  selector:
    app: stargazer-server  